apiVersion: v1
kind: Service
metadata:
  labels:
    app: karkee-app-staging-api
  name: api-service
  namespace: development
spec:
  ports:    
  - protocol: TCP
    port: 8080    
    targetPort: 8080
  selector:
    app: karkee-app-staging-api
status:
  loadBalancer: {}