---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: karkee-staging-letsencrypt
  namespace: ingress-nginx
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@karkee.biz
    privateKeySecretRef:
      name: secret-name
    solvers:
    - http01:
        ingress:
          class: nginx
---
---
apiVersion: v1
kind: Secret
metadata:
  name: karkee-staging-ingress-tls-secret
type: Opaque
data:
  ca.crt: -----BEGIN CERTIFICATE-----
MIIC8DCCAdigAwIBAgIULTLxErrc2hV8jnAqhzXDZDSbXq4wDQYJKoZIhvcNAQEL
BQAwGDEWMBQGA1UEAxMNS2Fya2VlIFNpZ25lcjAgFw0yMjAzMzEyMDM1MDBaGA8y
MTIyMDMwNzIwMzUwMFowFTETMBEGA1UEAxMKa2Fya2VlLmJpejBZMBMGByqGSM49
AgEGCCqGSM49AwEHA0IABA1oPYb412vxrwaeSDD/8UF0HNyk6Vyh8PMNCxuJF7Uj
XSRL7HKafCP/et4bcx+HC7BkB6+HD1b513nqd8AvsX+jgf0wgfowDgYDVR0PAQH/
BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwHQYDVR0O
BBYEFEcXXSiEknkAibLVGKCpkjjKwaG+MB8GA1UdIwQYMBaAFB73O95vU/ODi6Rx
Lls7ycXt7I6+MIGEBgNVHREEfTB7ghZhcGkuc3RhZ2luZy5rYXJrZWUuYml6ghht
eXNxbC5zdGFnaW5nLmthcmtlZS5iaXqCHXBocG15YWRtaW4uc3RhZ2luZy5rYXJr
ZWUuYml6ghxkYXNoYm9hcmQuc3RhZ2luZy5rYXJrZWUuYml6hwQifJFehwQjxZgV
MA0GCSqGSIb3DQEBCwUAA4IBAQCiuLcRn6fY7Uusktad3QSTR08xOlRS4u1g8krk
de7W27r664hzt1/ueyqc5gnuEll/g8Zm6li17KS9B7Ud/ALNDyb1bDgFXvFLOphn
rfOIGfLwnZpXIqIw7tdjro3+Chk3Csxo39BM0/OZPxt91EhG1JYbHLTRAk4e0KG9
TfHxLZ/qIisdeeZlo3NFAKQtcGsWPoslkmYMnRFfshcTDFy4Z3I6TNUAatsGB035
PFSEI0ElqnHVco1/J4rFprXKbv1IMfuJMLDBdioK5fxri1/DXIGLqAfuy2oZRFb0
hn1aOW7EuZZyYYY06VzaLI6MxaY3/cExw4pCrb9enzu1pV6l
-----END CERTIFICATE-----
  tls.crt: -----BEGIN CERTIFICATE-----
MIIC8DCCAdigAwIBAgIULUE1BTqOnjb06E1pGzdir4kgyrgwDQYJKoZIhvcNAQEL
BQAwGDEWMBQGA1UEAxMNS2Fya2VlIFNpZ25lcjAgFw0yMjAzMzEyMjI4MDBaGA8y
MTIyMDMwNzIyMjgwMFowFTETMBEGA1UEAxMKa2Fya2VlLmJpejBZMBMGByqGSM49
AgEGCCqGSM49AwEHA0IABA1oPYb412vxrwaeSDD/8UF0HNyk6Vyh8PMNCxuJF7Uj
XSRL7HKafCP/et4bcx+HC7BkB6+HD1b513nqd8AvsX+jgf0wgfowDgYDVR0PAQH/
BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwHQYDVR0O
BBYEFEcXXSiEknkAibLVGKCpkjjKwaG+MB8GA1UdIwQYMBaAFB73O95vU/ODi6Rx
Lls7ycXt7I6+MIGEBgNVHREEfTB7ghZhcGkuc3RhZ2luZy5rYXJrZWUuYml6ghht
eXNxbC5zdGFnaW5nLmthcmtlZS5iaXqCHXBocG15YWRtaW4uc3RhZ2luZy5rYXJr
ZWUuYml6ghxkYXNoYm9hcmQuc3RhZ2luZy5rYXJrZWUuYml6hwQifJFehwQjxZgV
MA0GCSqGSIb3DQEBCwUAA4IBAQAetoqCW2LKi37+agjkNfI81JH3XuxS1Lc0GSFY
UQ+7EyHKo5qYWPV7IPyitCS36+VguDVWj/W49WLzfqg5qvWWtRC2FCkL3suv8H+F
0AxpesU9yD9PzE5/mR+EhzXr21UI6JNOv8Pg21wpZMuVJ5m5PqUbEfoAkEvPa647
NjHB90ubTB88XtpEbraQ7mvw/Tzwam3ut9yNiYSWj02RJsKak1rUh/iiqj0ILArp
/+9Gvt7BAfaEIsdg/ys3sHM72CZDczV8H7f9yEvTzMy/LBR+BF68GIS80ZFhuweI
dGK/Eyvwy5j7KnA5lcLoshL2qiljANZgu75C5CHvcJniI2u3
-----END CERTIFICATE-----
  tls.key: -----BEGIN CERTIFICATE-----
MIIC8DCCAdigAwIBAgIULUE1BTqOnjb06E1pGzdir4kgyrgwDQYJKoZIhvcNAQEL
BQAwGDEWMBQGA1UEAxMNS2Fya2VlIFNpZ25lcjAgFw0yMjAzMzEyMjI4MDBaGA8y
MTIyMDMwNzIyMjgwMFowFTETMBEGA1UEAxMKa2Fya2VlLmJpejBZMBMGByqGSM49
AgEGCCqGSM49AwEHA0IABA1oPYb412vxrwaeSDD/8UF0HNyk6Vyh8PMNCxuJF7Uj
XSRL7HKafCP/et4bcx+HC7BkB6+HD1b513nqd8AvsX+jgf0wgfowDgYDVR0PAQH/
BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwHQYDVR0O
BBYEFEcXXSiEknkAibLVGKCpkjjKwaG+MB8GA1UdIwQYMBaAFB73O95vU/ODi6Rx
Lls7ycXt7I6+MIGEBgNVHREEfTB7ghZhcGkuc3RhZ2luZy5rYXJrZWUuYml6ghht
eXNxbC5zdGFnaW5nLmthcmtlZS5iaXqCHXBocG15YWRtaW4uc3RhZ2luZy5rYXJr
ZWUuYml6ghxkYXNoYm9hcmQuc3RhZ2luZy5rYXJrZWUuYml6hwQifJFehwQjxZgV
MA0GCSqGSIb3DQEBCwUAA4IBAQAetoqCW2LKi37+agjkNfI81JH3XuxS1Lc0GSFY
UQ+7EyHKo5qYWPV7IPyitCS36+VguDVWj/W49WLzfqg5qvWWtRC2FCkL3suv8H+F
0AxpesU9yD9PzE5/mR+EhzXr21UI6JNOv8Pg21wpZMuVJ5m5PqUbEfoAkEvPa647
NjHB90ubTB88XtpEbraQ7mvw/Tzwam3ut9yNiYSWj02RJsKak1rUh/iiqj0ILArp
/+9Gvt7BAfaEIsdg/ys3sHM72CZDczV8H7f9yEvTzMy/LBR+BF68GIS80ZFhuweI
dGK/Eyvwy5j7KnA5lcLoshL2qiljANZgu75C5CHvcJniI2u3
-----END CERTIFICATE-----
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "karkee-staging-letsencrypt"    
  name: karkee-staging-ingress
  namespace: development
spec:
  rules:
  - host: phpmyadmin.staging.karkee.biz
    http:
      paths:
      - backend:
          service:
            name: phpmyadmin-service
            port:
              number: 80
        pathType: ImplementationSpecific
  - host: api.staging.karkee.biz
    http:
      paths:
      - backend:
          service:
            name: api-service
            port:
              number: 8080
        pathType: ImplementationSpecific
  - host: mysql.staging.karkee.biz
    http:
      paths:
      - backend:
          service:
            name: mysql-service
            port:
              number: 3306
        pathType: ImplementationSpecific
  tls:
  - secretName: karkee-staging-ingress-tls-secret
status:
  loadBalancer:
    ingress:
    - ip: 34.124.145.94
