---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: karkee-app-staging-api-phpmyadmin
  name: phpmyadmin-deployment
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karkee-app-staging-phpmyadmin
  template:
    metadata:
      labels:
        app: karkee-app-staging-phpmyadmin
    spec:
      containers:
      - name: karkee-app-staging-phpmyadmin
        image: phpmyadmin/phpmyadmin
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
          - containerPort: 80
        env:
          - name: PMA_HOST
            value: mysql-service
          - name: PMA_PORT
            value: "3306"
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: root-password
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: karkee-app-staging-phpmyadmin
  name: phpmyadmin-service
  namespace: development
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32132
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: karkee-app-staging-phpmyadmin
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}