---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  namespace: development
  labels:
    app: karkee-app-staging-phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karkee-app-staging-phpmyadmin
  template:
    metadata:
      labels:
        app: karkee-app-staging-phpmyadmin
    spec:
      containers:
        - name: karkee-app-staging-phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql-service
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: root-password
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: development
  labels:
    app: karkee-app-staging-phpmyadmin
spec:
  type: NodePort
  selector:
    app: karkee-app-staging-phpmyadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80