---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: karkee-certificate2
  namespace: ingress-nginx
spec:
  domains:
    - phpmyadmin.staging.karkee.biz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  namespace: ingress-nginx
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
          - containerPort: 80
        env:
          - name: PMA_HOST
            value: mysql-service
          - name: PMA_PORT
            value: "3306"
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: root-password
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: karkee-app-staging
  name: api-service
  namespace: ingress-nginx
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32134
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 32135
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: karkee-app-staging
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}