---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: karkee-app-staging-api
  name: api-staging-deployment
  namespace: development
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: karkee-app-staging-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: karkee-app-staging-api
    spec:
      containers:
      - name: karkee-app-staging-api
        image: fdc101082/dev.api.karkee.biz:app-api-1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: karkee-app-staging-api
  name: api-service
  namespace: development
spec:
  externalTrafficPolicy: Cluster
  ports:    
  - name: http
    nodePort: 32130
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: karkee-app-staging-api
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

