apiVersion: v1
kind: Service
metadata:
  labels:
    app: karkee-app-staging-api
  name: api-service
  namespace: development
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: karkee-app-staging-api
  ports:
  - name: http
    nodePort: 32131
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}