apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: development
spec:
  selector:
    app: karkee-app-staging-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
status:
  loadBalancer: {}