apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: development
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: karkee-app-staging-mysql
  ports:
  - name: http
    nodePort: 32133
    port: 3306
    protocol: TCP
    targetPort: 3306
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}