apiVersion: v1
kind: Service
metadata:
    name: nginx-service
    namespace: development
    labels:
        app: karkee-app-staging-nginx
spec:
    ports:
        - name: http
          port: 80
          targetPort: 80
    selector:
        app: karkee-app-staging-nginx
    type: LoadBalancer
