apiVersion: v1
kind: Service
metadata:
    name: nginx-service
    namespace: development
    labels:
        app: karkee-app-staging-nginx
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: karkee-app-staging-nginx
  ports:
  - name: http
    nodePort: 32134
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
