-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgooBUVCqJZTJROXbi
ZwPcie1Q+azYENKH5oUMv9rlb06gCgYIKoZIzj0DAQehRANCAATO5PPaPZPR9bJs
zULhCncAcx2tJuGMTeHWdy90nRiWw7CESrf2PvwBWeHSQXlZJzPBBYyd9OgIigFf
HH8K/YP3
-----END PRIVATE KEY-----