---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: labsavvy-adminsandbox
  name: adminsandbox-labsavvy-deploy
  namespace: sandbox
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: labsavvy-adminsandbox
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: labsavvy-adminsandbox
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: sandbox
        - name: REACT_APP_BACKEND_URL
          value: https://apisb.labsavvy.com
        envFrom:
        - secretRef:
            name: mongodb-secret
        - secretRef:
            name: plaid-secret
        - secretRef:
            name: external-ingress-tls-lb-secret
        image: gcr.io/ls-sandbox-v1/adminsb_server:40040
        imagePullPolicy: Always
        name: labsavvy-adminsandbox
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 50m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: labsavvy-adminsandbox
  name: adminsandbox-service
  namespace: sandbox
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32421
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: labsavvy-adminsandbox
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

