---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: labsavvy-apisandbox
  name: apisandbox-labsavvy-deployment
  namespace: sandbox
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: labsavvy-apisandbox
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: labsavvy-apisandbox
    spec:
      containers:
      - command:
        - npm
        - run
        - start:server
        env:
        - name: NODE_ENV
          value: sandbox
        - name: API_PORT
          value: "8080"
        - name: API_URL
          value: https://apisb.labsavvy.com
        - name: APP_LINK_APPLE_APP_STORE
          value: https://apps.apple.com/us/app/labsavvy/id1479606330
        - name: APP_LINK_GOOGLE_PLAY_STORE
          value: https://play.google.com/store/apps/details?id=com.labsavvy
        - name: AUTH_PRE_REGISTER_TOKEN_TTL
          value: "1200000"
        - name: AUTH_RECOVER_TOKEN_TTL
          value: "1200000"
        - name: CLOUD_BUCKET_API_IMAGES
          value: sandbox-api-images
        - name: CLOUD_BUCKET_API_PDFS
          value: sandbox-api-pdfs
        - name: CLOUD_PROJECT_ID
          value: ls-sandbox-v1
        - name: MAILER_SMTP_HOST
          value: smtp.gmail.com
        - name: MAILER_SMTP_PORT
          value: "587"
        - name: MAILER_SMTP_TLS
          value: "true"
        - name: MAILER_X_MAILER
          value: LabSavvy service
        - name: PLATFORM_ADMIN_NAME
          value: Admin
        - name: PLATFORM_ADMIN_URL
          value: https://adminsb.labsavvy.com
        - name: PLATFORM_CMS_NAME
          value: CMS
        - name: PLATFORM_CMS_URL
          value: https://cmssb.labsavvy.com
        - name: PLATFORM_WEBAPP_NAME
          value: Webapp
        - name: PLATFORM_WEBAPP_URL
          value: https://portalsb.labsavvy.com
        - name: SENTRY_DSN
          value: https://db7fec9b632b45079d56f7ce2cfa818d@o281223.ingest.sentry.io/1506247
        - name: USE_API_DEBUGGING
          value: "false"
        - name: USE_API_TRACING
          value: "false"
        - name: USE_ECOMMERCE
          value: "true"
        - name: USE_ERROR_TRACKING
          value: "true"
        - name: USE_FIREBASE
          value: "true"
        - name: USE_GCLOUD
          value: "true"
        - name: USE_MAILER
          value: "true"
        - name: USE_SCHEDULER
          value: "false"
        envFrom:
        - secretRef:
            name: mongodb-secret
        - secretRef:
            name: mailer-secret
        - secretRef:
            name: sunrise-secret
        - secretRef:
            name: jwt-secret
        - secretRef:
            name: stripe-secret
        - secretRef:
            name: plaid-secret
        image: gcr.io/ls-sandbox-v1/apisb_server:400120
        imagePullPolicy: Always
        name: labsavvy-apisandbox
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 50m
          requests:
            cpu: 20m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: labsavvy-apisandbox
  name: apisandbox-service
  namespace: sandbox
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32100
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: labsavvy-apisandbox
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

