apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-phpmyadmin-deployment
  namespace: development
spec:
  selector:
    matchLabels:
      app: mysql-phpmyadmin
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql-phpmyadmin
    spec:
      containers:
      - name: karkee-staging-mysql
        image: mysql:5.7
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
        - containerPort: 3306
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            subPath: "mysql"
            name: mysql-data
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: root-password
      - name: karkee-app-staging-phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
          resources:
        volumeMounts:
          - name: nginx-config-volume
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
          - name: www-storage
            mountPath: /var/www/phpmyadmin/        
        env:
          - name: PMA_HOST
            value: mysql-service
          - name: PMA_PORT
            value: "3306"
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: root-password
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: www-storage
          persistentVolumeClaim:
            claimName: pv-www-claim
        - name: nginx-config-volume
          configMap:
            name: nginx-config