---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: karkee-app-staging-api
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: api-staging-deployment
  namespace: development
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: karkee-app-staging-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: karkee-app-staging-api
    spec:
      containers:
      - name: karkee-app-staging-api
        image: gcr.io/agile-infinity-329404/dev.api.karkee.biz:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/api.conf
          subPath: api.conf
        - name: www-storage
          mountPath: /var/www/html/api/web
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: www-storage
        persistentVolumeClaim:
          claimName: pv-www-claim
      - name: nginx-config-volume
        configMap:
          name: nginx-config