---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: karkee-app-staging-api
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: api-staging-deployment
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karkee-app-staging-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: karkee-app-staging-api
    spec:
      containers:
      - name: karkee-app-staging-api
        image: fdc101082/dev.api.karkee.biz:app-api-1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/api.conf
          subPath: api.conf
        - name: www-storage
          mountPath: /var/www/html/api/web
      - name: nginx
        image: nginx:alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: www-storage
          mountPath: /srv/app/
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: www-storage
        persistentVolumeClaim:
          claimName: pv-www-claim
      - name: nginx-config-volume
        configMap:
          name: nginx-config