apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: karkee-app-staging
  name: karkee-staging-deployment
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karkee-app-staging
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: karkee-app-staging
    spec:
      containers:
      - name: karkee-app-staging-api
        image: fdc101082/dev.api.karkee.biz:app-api-XXXX
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
          name: http
          protocol: TCP
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/api.conf
          subPath: apikarkee.conf
        - name: www-storage
          mountPath: /var/www/html
      - name: karkee-app-staging-apicarkee
        image: fdc101082/dev.api.karkee.biz:app-apikarkee-1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/apicarkee.conf
          subPath: apikarkee.conf
        - name: www-storage
          mountPath: /var/www/html
      - name: nginx
        image: nginx:alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: www-storage
          mountPath: /var/www/html
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: ""
      volumes:
      - name: www-storage
        persistentVolumeClaim:
          claimName: pv-www-claim
      - name: nginx-config-volume
        configMap:
          name: nginx-config
