---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: karkee-app-staging-mysql
  name: mysql-secrets
  namespace: development
type: Opaque
data:
    root-password: MDEuKSAwMV9TdGFnaW5nL0thcmtlZS9BcHAjMDFAQXBpOjEuMC1BbHBoYQ==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: karkee-app-staging-mysql
  name: mysql-deployment
  namespace: development
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: karkee-app-staging-mysql
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: karkee-app-staging-mysql
    spec:
      containers:
      - name: karkee-app-staging-mysql
        image: mysql:5.7
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
          - containerPort: 3306
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            subPath: "mysql"
            name: mysql-data
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: root-password      
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc