apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-pvc
  namespace: development
spec:
    storageClassName: standard
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
